---

- hosts: all
  become: true
  tasks:

  - name: install apache package and add php support for apache
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"] and ansible_distribution_version == "22.04"