---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: copy default html files for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  roles:
    - base
  
- hosts: workstations
  become: true
  tasks:
  roles:
    - workstations

- hosts: web_servers
  become: true
  tasks:
  roles:
    - web_servers

- hosts: db_servers
  become: true
  tasks:
  roles:
      - db_servers