- name: Create simone User
  tags: always
  user:
    name: simone
    groups: root
  
- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: ""

- name: add ssh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQI2pdCWq8ds3f9CWhh+pKqbxxmFtOMBbPdXRnfFUQILNb7vBMFHjnVvyyZEXd7xuZsQx3cu95m5vR8I4kRg3qYOqFYeJPHfUpvwcHMz895Cgx3o6lX2rnRty4MVMd5jtaI7UWgDLoiVZ2uoXpgh/4qyQ1eu3KXS+jF5GEJzPbeCm13HWfLqlFQnWVXQdtKmH9ocNqnWZ1SDXkUuGTBm6x8VfDp9364V3VajOzS8GzlGXv5p7S9sAyRWmOqrPh9vgjtb0XOcDounSDpMLm77jo3Hc3btRRacGywz3D2MWhj3myo4dYzTVeyiqfdaIOFdP5QJzqHg8O1rep8yM49JzRgMN1mETWSy/ylBSRYfx5T0Yf8cbWf+RCb5gYbhYD5Jyjhp9W2gUytbpWdw+xuGORbaGP4K5GLJp00ikjPGhqEz0pTRrsKAgi2gNFNzuBxBMoD0Vm230UbFd1lfeyEw9byy0CqxVPHRAyuYMzurJSBBOCWcEJVFUutPSKLVM7NVM= giri.adhittana@BA-00024762.local"

- name: add sudoers file for simone
  tags: always
  copy:
    src: sudoers_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root