- name: install mariadb package (Ubuntu)
  tags: db,maria,ubuntu
  package:
    name: 
      - "{{ mariadb_package }}"
    state: latest
    update_cache: yes
  when: ansible_distribution in ["Ubuntu","Debian"] and ansible_distribution_version == "22.04"